### ISSUE TITLE
no rule to make target libicutu.a

### ISSUE THREAD

**Issue by rozen03** [NXij/tdesktop-dark#2]
Hi! I've been trying to build this guidede by  https://github.com/NXij/tdesktop-dark/blob/0.10.19/doc/building-cmake.md
when i reach the point of:
 "To make Debug version go to /home/user/TBuild/tdesktop/out/Debug and run

make
"

i get this: 
make[2]: *** No rule to make target '/usr/lib/libicutu.a', needed by 'MetaLang'.  Stop.
CMakeFiles/Makefile2:721: recipe for target 'CMakeFiles/MetaLang.dir/all' failed
make[1]: *** [CMakeFiles/MetaLang.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by NXij** [comment]
http://stackoverflow.com/questions/40239164/telegram-compilation-processno-rule-to-make-target-usr-lib-libicutu-a

Check that

**Comment by rozen03** [comment]
yeah, but i needed more guide, the solution i found was here.....
https://www.raspberrypi.org/forums/viewtopic.php?t=164737&p=1062831
i needed to configure ICU with --enable-static
